variables:
  - SONAR_URL: 'http://repository.dimas-maryanto.com:8024'
  - SONAR_AUTH: '2eb155ca79462a2d77bdd57f0fba32cce13bd9de'

stages:
  - test
  - build
  - package
  - deploy

cache:
  paths:
    - .m2/repository

code_analys:
  stage: build
  script:
     - mvn sonar:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_AUTH

deploy_snapshot:
  stage: deploy
  script:
    - 'mvn clean test install deploy'
  only:
    - /-snapshot$/
  artifacts:
    paths:
      - target/*.jar

deploy_releash:
  stage: deploy
  script:
    - 'mvn clean test install deploy'
  only:
    - /-final$/
  artifacts:
    paths:
      - target/*.jar