stages:
  - test
  - build
  - package
  - deploy

cache:
  paths:
    - .m2/repository

deploy_snapshot:
  stage: deploy
  script:
    - 'mvn clean test install deploy'
  only:
    - /-snapshot$/
  artifacts:
    paths:
      - target/*.jar

deploy_releash:
  stage: deploy
  script:
    - 'mvn clean test install deploy'
  only:
    - /-release$/
  artifacts:
    paths:
      - target/*.jar