stages:
  - test
  - build
  - package
  - deploy

cache:
  paths:
    - .m2/repository

validate: 
  stage: test
  script:
    - 'mvn test'

deploy_snapshot:
  stage: deploy
  script:
    - 'mvn install deploy'
  only:
    - /-snapshot$/
  artifacts:
    paths:
      - target/*.jar

deploy_releash:
  stage: deploy
  script:
    - 'mvn install deploy'
  only:
    - /-final$/
  artifacts:
    paths:
      - target/*.jar