stages:
  - test
  - build
  - package
  - deploy

cache:
  paths:
    - .m2/repository

code_analys:
  stage: build
  script:
     - mvn clean package sonar:sonar -Dsonar.host.url=$URL_SONAR -Dsonar.login=$AUTH_SONAR

deploy_snapshot:
  stage: deploy
  script:
    - 'mvn clean test install deploy'
  only:
    - /-snapshot$/
  artifacts:
    paths:
      - target/*.jar

deploy_releash:
  stage: deploy
  script:
    - 'mvn clean test install deploy'
  only:
    - /-final$/
  artifacts:
    paths:
      - target/*.jar