stages:
  - test
  - build
  - package
  - deploy

cache:
  paths:
    - .m2/repository

code_analys:
  image: repository.dimas-maryanto.com:8086/maven:3.6-jdk-8
  stage: build
  script:
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package
    - mvn install
    - mvn sonar:sonar -Dsonar.projectKey=$PROJECT_KEY -Dsonar.host.url=$URL_SONAR -Dsonar.login=$AUTH_SONAR -Dmaven.test.failure.ignore=false
  only:
    - /-release$/

deploy_snapshot:
  image: repository.dimas-maryanto.com:8086/maven:3.6-jdk-8
  stage: deploy
  script:
    - 'mvn clean install deploy'
  only:
    - /-snapshot$/
  artifacts:
    paths:
      - target/*.jar

deploy_releash:
  image: repository.dimas-maryanto.com:8086/maven:3.6-jdk-8
  stage: deploy
  script:
    - 'mvn clean install deploy'
  only:
    - /-release$/
  artifacts:
    paths:
      - target/*.jar
